# Generated by Django 2.1 on 2018-11-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nie_hub', '0006_auto_20181104_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_link', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('branch', models.CharField(choices=[('CE', 'CE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ISE', 'ISE'), ('ME', 'ME'), ('IPE', 'IPE')], max_length=3)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
            ],
        ),
        migrations.AddField(
            model_name='attachments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts'),
        ),
    ]
