# Generated by Django 2.1 on 2018-11-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nie_hub', '0006_auto_20181104_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('body', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('venue', models.CharField(max_length=30, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('item_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=3, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Trousers', 'Trousers'), ('Caps', 'Caps'), ('Others', 'Others')], max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_items',
            fields=[
                ('item_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('quantity_sold', models.IntegerField()),
                ('size', models.CharField(max_length=3, null=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Trousers', 'Trousers'), ('Caps', 'Caps'), ('Others', 'Others')], max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='nie_hub.User')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='nie_hub.User')),
            ],
        ),
        migrations.CreateModel(
            name='Waiting_items',
            fields=[
                ('item_waiting_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_quantity', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
                ('item_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Item_details')),
            ],
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Items'),
        ),
    ]
