# Generated by Django 2.1 on 2018-11-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nie_hub', '0006_auto_20181104_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('book_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('CE', 'CE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ISE', 'ISE'), ('ME', 'ME'), ('IPE', 'IPE')], max_length=3)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_books',
            fields=[
                ('book_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('title1', models.CharField(max_length=60, null=True)),
                ('author1', models.CharField(max_length=30, null=True)),
                ('edition1', models.IntegerField(null=True)),
                ('price1', models.IntegerField(null=True)),
                ('buyer_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id1', to='nie_hub.User')),
                ('owner_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id1', to='nie_hub.User')),
            ],
        ),
        migrations.CreateModel(
            name='Waiting_books',
            fields=[
                ('book_wait_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('book_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book_details')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
            ],
        ),
        migrations.AddField(
            model_name='book_details',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
        migrations.AddField(
            model_name='book_details',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User'),
        ),
    ]
