# Generated by Django 2.0.9 on 2018-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=3)),
                ('sem', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('usn', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
