# Generated by Django 2.1 on 2018-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0002_auto_20181006_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('CE', 'CE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ISE', 'ISE'), ('ME', 'ME'), ('IPE', 'IPE')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
