# Generated by Django 2.1 on 2018-11-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0003_auto_20181101_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
