# Generated by Django 2.1 on 2018-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0004_auto_20181102_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
